#!/bin/bash
### git++ ###

export RootDir=${RootDir:-$(dirname "$(readlink -f "$0")")}

## Include bootstrap
[ ! -f "${RootDir}/bootstrap" ] && echo -e "\\e[1;31m(50) FATAL ERROR: Missing 'bootstrap' file\\e[0m" && exit 50
# shellcheck disable=SC1090
. "${RootDir}/bootstrap"

## Parse options
(($#)) && export OPTSARGS=("$@")
core.options
shift "$((OPTIND-1))"

result=$(core.commandExists "$1")
status=$?
[ $status != 0 ] && core.exit "$result" $status

## Execute [command]
export Command="$result"
# shellcheck disable=SC2048,2086
shift && "$Command" $*
