#!/bin/bash
### git++ ###

export RootDir=${RootDir:-$(dirname "$(readlink -f "$0")")}

## Include bootstrap
[ ! -f "${RootDir}/bootstrap" ] && echo -e "\\e[1;31m(50) FATAL ERROR: Missing 'bootstrap' file\\e[0m" && exit 50
# shellcheck source=bootstrap
. "${RootDir}/bootstrap"

## Get [command] argument
[ -z "$1" ] && printer.warning "Missing [command] argument" && exit 1
command="$1"

if [[ -x "${RootDir}/command/${command}.sh" ]]; then
    export Command="${RootDir}/command/${command}.sh"
elif [[ -x "${RootDir}/usr/command/${command}.sh" ]]; then
    export Command="${RootDir}/usr/command/${command}.sh"
else
    printer.fatalerror "script ${Command} is not executable"
    exit 50
fi

## Execute [command]
shift && "$Command" "$*"
