#!/bin/bash
### git++ ###
export Verbose=true

export RootDir=${RootDir:-$(dirname "$(readlink -f "$0")")}

## Include bootstrap
[ ! -f "${RootDir}/bootstrap" ] && echo -e "\\e[1;31m(50) FATAL ERROR: Missing 'bootstrap' file\\e[0m" && exit 50
# shellcheck disable=SC1090
. "${RootDir}/bootstrap"

result=$(core.command_exists "$1")
status=$?
[ $status != 0 ] && core.exit "$result" $status

export Command="$result"
## Execute [command]
shift && "$Command" "$*"
